---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: zerozero
  name: zerozero
spec:
  type: LoadBalancer
  ports:
  - name: zerozero
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    service: zerozero
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: redis
  name: redis
spec:
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
  selector:
    app: redis
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - image: redis:3.2.3
        name: redis
        ports:
        - name: redis
          containerPort: 6379
      restartPolicy: Always
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: zerozero
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: zerozero
    spec:
      containers:
      - image: game:latest
        imagePullPolicy: IfNotPresent
        name: zerozero
        env:
          - name: REDIS_URL
            value: redis://redis:6379/0
        resources:
          requests:
            memory: 100Mi
            cpu: 1m
          limits:
            memory: 1000Mi
            cpu: 250m
        ports:
        - containerPort: 8081
          hostPort: 8081
          protocol: TCP
      restartPolicy: Always
---
apiVersion: batch/v1
kind: Job
metadata:
  name: spawn-world-and-coins
spec:
  template:
    spec:
      containers:
      - name: spawn-world-and-coins
        image: game:latest
        imagePullPolicy: IfNotPresent
        command: ["zerozero-new-world"]
        env:
          - name: REDIS_URL
            value: redis://redis:6379/0
        resources:
          requests:
            memory: 100Mi
            cpu: 1m
          limits:
            memory: 1000Mi
            cpu: 250m
      restartPolicy: Never
  backoffLimit: 4
